### ISSUE TITLE
功能性建议

### ISSUE THREAD

**Issue by tonyycdd** [tu10ng/autoflap#2]
### `很好的idea, 使我的升力变大`
感觉可以结合8111的襟翼震颤值来自动化襟翼, 比方说维持在襟翼震颤80%的襟翼开度, 这样就不做每个飞机的预设值了, 并某种程度上优化全速度段俯仰轴机动. (副作用可能是滚转速度和侧滑程度)

然后可以用一个按键控制开关, 以防俯冲脱离或者高速拖带的时候造成问题. (类似于BVR / BFM模式切换, 我看readme里按键是pause, 能不能改成可选的)

**Comment by tu10ng** [comment]
1. 根据隐居寒天所说, 如果我理解正确, 维持在襟翼震颤80%的襟翼开度不会得到最佳的回转速度. 同时, 由于wt每隔一段时间改一次启动, 所以最佳的襟翼值需要经常手动测量更新. @SeclusionalAgar

2. 目前固定`pause`键的原因是`pause`不常用, 可以用鼠标/键盘驱动把某个键映射到`pause`上. 
改成其他按键是可行的, 只要把源码中所有的`pause`查找替换成其他键就可以. 暂时不打算动.

**Comment by tonyycdd** [comment]
> 1. 根据隐居寒天所说, 如果我理解正确, 维持在襟翼震颤80%的襟翼开度不会得到最佳的回转速度. 同时, 由于wt每隔一段时间改一次启动, 所以最佳的襟翼值需要经常手动测量更新. @SeclusionalAgar
> 2. 目前固定`pause`键的原因是`pause`不常用, 可以用鼠标/键盘驱动把某个键映射到`pause`上.
>    改成其他按键是可行的, 只要把源码中所有的`pause`查找替换成其他键就可以. 暂时不打算动.

1确实如此, 不能这样做, 只是提供一个思路(或许可以参考一个那个回转率), 毕竟实现了可以自动化了, 不用辛苦大佬挨个测试了, 希望最终能实现吧
2了解, 谢谢解答

**Comment by SeclusionalAgar** [comment]
这是不可能实现的，因为wt的襟翼代码比较复杂，是否会被吹飞是一个概率分布；相比于该项功能，升级为无极襟翼的意义更大一些。
